### ISSUE TITLE
Parallel publish of multiple models to same AAS server fails

### ISSUE THREAD

**Issue by ckupferschmid** [liprec/vsts-release-aas#27]
Error message:

Error during adding firewall rule (Firewall rule names should be unique. Duplicate name vsts-release-aas-rule is not allowed.)
Firewall rule names should be unique. Duplicate name vsts-release-aas-rule is not allowed.

**Comment by richardswinbank** [comment]
I experienced this error after a prior deployment failure. The deployment failure was my fault - AAS was paused! - but it looks like the task didn't clean up after itself post-failure. On the next run, the task failed because the rule was still there.

It would be useful if the task could remove the firewall rule after failure and/or check for its existence before attempting to create it.
