### ISSUE TITLE
Error While deploying using SPN

### ISSUE THREAD

**Issue by shameeds** [liprec/vsts-release-aas#37]
Hi @liprec ,

We are getting below error while deploying model to AAS using SPN.

Could you please help us to resolve this.
"
Error during deploying the model (Authentication failed: User ID and Password are required when user interface is not available.)
"

**Comment by liprec** [comment]
Hi @shameeds,

Did you set the `Login type (loginType)` to `Service Principal`?

-JP

**Comment by D-to-the-K** [comment]
In my case, I had to recreate this extension from scratch instead of installing it, and in my case I had to call `Invoke-ASCmd` with both the `-Credential` and the `-ServicePrincipal` arguments [here](https://github.com/liprec/vsts-release-aas/blob/c7d72dd39a68232714819cb79c0c3c8dfc7ddd4c/deploy-aas-db/v1/deploy-aas-db.psm1#L242). Could be due to another reason, though.

Excellent work, by the way!
