### ISSUE TITLE
TMSL error server

### ISSUE THREAD

**Issue by Philippe-ecomcs** [liprec/vsts-release-aas#95]
Hello,

in version 1.3.6 script run fine
in 1.5.8 i'm geting this error
2022-02-16T12:28:12.9879983Z ##[error]System.Management.Automation.RuntimeException: No resource found with serverName XXXprod, serverType Microsoft.AnalysisServices/servers in subscription f41XXX-CCXC2-XXXX-XXX-XXXXXXb0a90. Specify the correct serverName/serverType and try again.

it's appear that my server XXXprod was never inside the good ressource group of the subscription but in another ressource group of the same subscription.
my solution has been to create new connection service to the other ressource and it's ok, but however i' like to know if any change in the upgrade can occur this issue ? 

Thx a lot

**Comment by liprec** [comment]
This is because the latest version is using the Azure REST APIs to add/remove the firewall and those APIs are hierarchal oriented and therefore this error was thrown as the server was not in the expected resourcegroup. In the previous version this was not an issue with the PowerShell cmdlets as every AAS service has a unique url.

**Comment by Philippe-ecomcs** [comment]
thank you, this allows me to confirm our diagnosis and understand the reasons for our issue.
